version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer
    ports:
      - "8080:8080"
    volumes:
      - ./consumer/uploads:/app/uploads
    networks:
      - media-net

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: producer
    depends_on:
      - consumer
    volumes:
      - ./producer/videos:/app/videos
    networks:
      - media-net
    command: ["java", "-jar", "app.jar"]

networks:
  media-net:
