FROM openjdk:17-jdk-slim as builder

WORKDIR /app

COPY . .

RUN ./gradlew :consumer:build --no-daemon

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/consumer/build/libs/*.jar app.jar
VOLUME /uploads
EXPOSE 8080

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["java", "-jar", "app.jar"]