FROM gradle:7.6-jdk17 AS build

WORKDIR /app
    
COPY . .
    
RUN gradle :consumer:build -x test
    
FROM eclipse-temurin:17-jre
    
WORKDIR /app
    

RUN apt-get update && \
        apt-get install -y ffmpeg && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*
    

COPY --from=build /app/consumer/build/libs/*.jar /app/app.jar
    
VOLUME /uploads
EXPOSE 8080
    
CMD ["java", "-jar", "app.jar"]
    